import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { getLocaleDir } from './locales.js';

/**
 * Ensure the i18n configuration file and locale files exist.
 * Creates them if they don't.
 *
 * @param {string} cwd - Project root
 * @param {object} project - Detected project info
 * @param {string} from - Source language code
 * @param {string} to - Target language code
 * @param {string} [customLocaleDir] - Optional override for locale directory
 */
export async function ensureI18nSetup(cwd, project, from, to, customLocaleDir) {
  const localeDir = customLocaleDir || getLocaleDir(cwd, project);
  mkdirSync(localeDir, { recursive: true });

  // Ensure locale JSON files exist
  for (const lang of [from, to]) {
    const localePath = join(localeDir, `${lang}.json`);
    if (!existsSync(localePath)) {
      writeFileSync(localePath, '{}\n', 'utf-8');
      console.log(chalk.green(`  ✓ Created ${localePath}`));
    }
  }

  if (project.type === 'vue') {
    await ensureVueI18n(cwd, project, from, to, localeDir);
  } else if (project.type === 'react') {
    await ensureReactI18n(cwd, project, from, to, localeDir);
  } else {
    await ensureVanillaI18n(cwd, from, to, localeDir);
  }
}

async function ensureVueI18n(cwd, project, from, to, localeDir) {
  const i18nFile = join(cwd, 'src', 'i18n.js');

  if (existsSync(i18nFile)) {
    console.log(chalk.gray('  → i18n.js already exists, skipping setup'));
    return;
  }

  const isVue3 = project.usesCompositionApi;
  const relLocale = localeDir.replace(cwd, '.').replace(/\\/g, '/');

  let content;
  if (isVue3) {
    content = `import { createI18n } from 'vue-i18n';
import ${from} from '${relLocale}/${from}.json';
import ${to} from '${relLocale}/${to}.json';

const i18n = createI18n({
  legacy: false,
  locale: '${from}',
  fallbackLocale: '${from}',
  messages: {
    ${from},
    ${to},
  },
});

export default i18n;
`;
  } else {
    content = `import Vue from 'vue';
import VueI18n from 'vue-i18n';
import ${from} from '${relLocale}/${from}.json';
import ${to} from '${relLocale}/${to}.json';

Vue.use(VueI18n);

const i18n = new VueI18n({
  locale: '${from}',
  fallbackLocale: '${from}',
  messages: {
    ${from},
    ${to},
  },
});

export default i18n;
`;
  }

  mkdirSync(join(cwd, 'src'), { recursive: true });
  writeFileSync(i18nFile, content, 'utf-8');
  console.log(chalk.green(`  ✓ Created ${i18nFile}`));
  console.log(chalk.yellow(`  ⚠ Don't forget to install vue-i18n: npm install vue-i18n`));
  console.log(chalk.yellow(`  ⚠ Import and use i18n in your main.js/main.ts`));
}

async function ensureReactI18n(cwd, project, from, to, localeDir) {
  const i18nFile = join(cwd, 'src', 'i18n.js');

  if (existsSync(i18nFile)) {
    console.log(chalk.gray('  → i18n.js already exists, skipping setup'));
    return;
  }

  const relLocale = localeDir.replace(cwd, '.').replace(/\\/g, '/');

  const content = `import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import ${from} from '${relLocale}/${from}.json';
import ${to} from '${relLocale}/${to}.json';

i18n.use(initReactI18next).init({
  resources: {
    ${from}: { translation: ${from} },
    ${to}: { translation: ${to} },
  },
  lng: '${from}',
  fallbackLng: '${from}',
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
`;

  mkdirSync(join(cwd, 'src'), { recursive: true });
  writeFileSync(i18nFile, content, 'utf-8');
  console.log(chalk.green(`  ✓ Created ${i18nFile}`));
  console.log(chalk.yellow(`  ⚠ Don't forget to install: npm install i18next react-i18next`));
  console.log(chalk.yellow(`  ⚠ Import './i18n' in your index.js/App.js`));
}

async function ensureVanillaI18n(cwd, from, to, localeDir) {
  const i18nFile = join(cwd, 'i18n.js');

  if (existsSync(i18nFile)) {
    console.log(chalk.gray('  → i18n.js already exists, skipping setup'));
    return;
  }

  const content = `/**
 * Simple i18n for vanilla JS — generated by bctranslate
 */
(function () {
  const locales = {};
  let currentLocale = '${from}';

  async function loadLocale(lang) {
    if (locales[lang]) return;
    const resp = await fetch('./locales/' + lang + '.json');
    locales[lang] = await resp.json();
  }

  function t(key, params) {
    const msg = (locales[currentLocale] && locales[currentLocale][key]) || key;
    if (!params) return msg;
    return msg.replace(/\\{(\\w+)\\}/g, function (_, k) {
      return params[k] !== undefined ? params[k] : '{' + k + '}';
    });
  }

  async function setLocale(lang) {
    await loadLocale(lang);
    currentLocale = lang;
    // Re-translate all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      const key = el.getAttribute('data-i18n');
      el.textContent = t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
    });
    document.querySelectorAll('[data-i18n-title]').forEach(function (el) {
      el.title = t(el.getAttribute('data-i18n-title'));
    });
  }

  // Auto-init
  loadLocale('${from}');
  loadLocale('${to}');

  window.i18n = { t: t, setLocale: setLocale, loadLocale: loadLocale };
})();
`;

  writeFileSync(i18nFile, content, 'utf-8');
  console.log(chalk.green(`  ✓ Created ${i18nFile}`));
  console.log(chalk.yellow(`  ⚠ Add <script src="i18n.js"></script> to your HTML`));
}