/**
 * Simple i18n for vanilla JS — generated by bctranslate
 */
(function () {
  const locales = {};
  let currentLocale = 'en';

  async function loadLocale(lang) {
    if (locales[lang]) return;
    const resp = await fetch('./locales/' + lang + '.json');
    locales[lang] = await resp.json();
  }

  function t(key, params) {
    const msg = (locales[currentLocale] && locales[currentLocale][key]) || key;
    if (!params) return msg;
    return msg.replace(/\{(\w+)\}/g, function (_, k) {
      return params[k] !== undefined ? params[k] : '{' + k + '}';
    });
  }

  async function setLocale(lang) {
    await loadLocale(lang);
    currentLocale = lang;
    // Re-translate all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      const key = el.getAttribute('data-i18n');
      el.textContent = t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
    });
    document.querySelectorAll('[data-i18n-title]').forEach(function (el) {
      el.title = t(el.getAttribute('data-i18n-title'));
    });
  }

  // Auto-init
  loadLocale('en');
  loadLocale('fr');

  window.i18n = { t: t, setLocale: setLocale, loadLocale: loadLocale };
})();
